name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Say Goodbye
      run: echo "\n\n************GoodBye****************\n"
  send-mail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2
      - name: Send Email
        run: |
          aws ses send-email \
            --from "kgy556@gmail.com"
            --destination "ToAddress=kgy556@naver.com"
            --message "Subjet={Data=[SDS-2026] 김경연},Body={Text={Data=행복한 주말 보내세요👍👍}}"
